# Generated by Django 3.1.3 on 2020-11-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_popular', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField(blank=True, choices=[(1, 'South America'), (2, 'Middle East'), (3, 'Africa')], null=True)),
                ('hot', models.BooleanField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffees', to='testapp.cafe')),
            ],
        ),
    ]
