# Generated by Django 3.1.3 on 2020-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='flavor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
