name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd backend/dockertest
        python manage.py test
    - name: Run on localserver
      run: |
        cd backend/dockertest
        nohup python manage.py runserver localhost:8000 &
    - name: Run ZAP
      uses: zaproxy/action-baseline@v0.4.0
      with:
        target: "localhost:8000"
        
